version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - sony-mathew
  - sojan-official
  - subintp
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.93.0
  - dependency-name: slack-ruby-client
    versions:
    - 0.16.0
  - dependency-name: scout_apm
    versions:
    - 4.0.3
  - dependency-name: valid_email2
    versions:
    - 3.5.0
  - dependency-name: groupdate
    versions:
    - 5.2.1
  - dependency-name: redis-namespace
    versions:
    - 1.8.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - pranavrajs
  - nithindavid
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: ionicons
    versions:
    - 5.3.0
    - 5.4.0
    - 5.5.0
